# Networking issue: make sure public profile does not block all connections
version: '3.3'

services:
  web:
    restart: always
    build: './app'
    ports:
      - "3060:3000"
    volumes:
      - "./app:/usr/src/app"
    stdin_open: true
    tty: true
    container_name: tb-mobile-app
